# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project


# Warnings currently triggered by your code
- ignore: {name: "Use module export list"}
- ignore: {name: "Use print"}
- ignore: {name: "Redundant lambda"}
- ignore: {name: "Avoid reverse"}
- ignore: {name: "Redundant bracket"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Use String"}
- ignore: {name: "Unused LANGUAGE pragma"}
- ignore: {name: "Use zipWithM_"}
- ignore: {name: "Use void"}
- ignore: {name: "Eta reduce"}
- ignore: {name: "Use let"}
- ignore: {name: "Use mapM"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Use elemIndices"}
- ignore: {name: "Use foldr"}
- ignore: {name: "Parse error"}
- ignore: {name: "Use foldl"}
- ignore: {name: "Use fmap"}
- ignore: {name: "Use if"}
- ignore: {name: "Redundant map"}
- ignore: {name: "Use map once"}
- ignore: {name: "Use camelCase"}
- ignore: {name: "Use list literal"}
- ignore: {name: "Use second"}
- ignore: {name: "Redundant guard"}
- ignore: {name: "Use Just"}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Redundant return"}
- ignore: {name: "Redundant do"}
- ignore: {name: "Use when"}
- ignore: {name: "Redundant $"}
- ignore: {name: "Reduce duplication"}
- ignore: {name: "Use fromMaybe"}
- ignore: {name: "Fix pragma markup"}
- ignore: {name: "Use span"}
- ignore: {name: "Use catMaybes"}
- ignore: {name: "Use intercalate"}


# Specify additional command line arguments
#
# - arguments: [--color, --cpp-simple, -XQuasiQuotes]


# Control which extensions/flags/modules/functions can be used
#
# - extensions:
#   - default: false # all extension are banned by default
#   - name: [PatternGuards, ViewPatterns] # only these listed extensions can be used
#   - {name: CPP, within: CrossPlatform} # CPP can only be used in a given module
#
# - flags:
#   - {name: -w, within: []} # -w is allowed nowhere
#
# - modules:
#   - {name: [Data.Set, Data.HashSet], as: Set} # if you import Data.Set qualified, it must be as 'Set'
#   - {name: Control.Arrow, within: []} # Certain modules are banned entirely
#
# - functions:
#   - {name: unsafePerformIO, within: []} # unsafePerformIO can only appear in no modules


# Add custom hints for this project
#
# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}


# Turn on hints that are off by default
#
# Ban "module X(module X) where", to require a real export list
# - warn: {name: Use explicit module export list}
#
# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}
#
# Generalise map to fmap, ++ to <>
# - group: {name: generalise, enabled: true}


# Ignore some builtin hints
# - ignore: {name: Use let}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules


# Define some custom infix operators
# - fixity: infixr 3 ~^#^~


# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
